# Generated by Django 3.2.16 on 2022-11-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('BooksId', models.AutoField(primary_key=True, serialize=False)),
                ('BooksName', models.CharField(max_length=500)),
                ('EbooksAuthor', models.CharField(max_length=500)),
                ('EbooksGenre', models.CharField(max_length=500)),
                ('EbookReview', models.IntegerField()),
                ('Favourite', models.CharField(max_length=500)),
            ],
        ),
    ]
